---
version: "3.8"

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile-test
    links:
      - tor
  tor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SOCKS_HOSTNAME=0.0.0.0
