# hadolint ignore=DL3006
FROM alpine:3.21.0@sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45

HEALTHCHECK NONE

ENTRYPOINT []

ARG USER_NAME=default
ARG USER_HOME=/home/default
ARG USER_ID=1000
ARG USER_GECOS=Default

# hadolint ignore=DL3018
RUN apk update \
 && apk add curl \
 && rm -rf /var/cache/apk/*

RUN adduser \
  --home "${USER_HOME}" \
  --uid "${USER_ID}" \
  --gecos "${USER_GECOS}" \
  --disabled-password \
  "${USER_NAME}"

ENV HOME="${USER_HOME}"

USER "${USER_NAME}"

WORKDIR "${HOME}"

# sleep 60s to make sure that container survived its own healthcheck
CMD ["/bin/sh", "-c", "/bin/sleep 60 ; /usr/bin/curl -i -s -S -f --socks5 tor:9050 --socks5-hostname tor:9050 https://check.torproject.org/api/ip"]
